### PR TITLE
Rainbows Unauthorized Fees

### PR DESCRIPTION
**Pull request by DayOfShah**
Hello all,
I have written previously about Rainbow falsely advertising a "free mint" on its app, and then subsequently charging an ethereum fee (in addition to the gas required to mint the NFT) without my knowledge or consent. When this matter was brought to the attention of Rainbow representatives, Rainbow inexplicably advised me to contact the Ethereum Foundation, to recoup the funds owed to me by Rainbow. 

Rainbow has continued to attempt to evade accountability. Thus I am asking the broader community for advice and assistance on resolving this matter. I am also kindly requesting that Rainbow stops attempting to conceal and obscure this matter, including its deleting of these communications, until this matter is resolved.  

The only way to communicate with Rainbow representatives has been on Github. In response, Rainbow has attempted to delete all evidence of these communications, and then communicating with me privately, while exerting no actual effort in resolving this matter, as demonstrated by Rainbow's latest response: 

On Sun, May 12, 2024 at 9:59 AM MK <[notifications@github.com](mailto:notifications@github.com)> wrote:
 **I know this is super frustrating, but please let's keep the conversation in this discussion [#1960](https://github.com/rainbow-me/rainbowkit/discussions/1960). Like i said the team is looking at this issue and we'll contact you back as soon as possible. The issue is unknown at the moment and our team is investigating this. Thanks for your patience 🙏**

—

**I am requesting the community's help in seeking a resolution to this matter, and ensuring Rainbow holds itself accountable for its actions. I am also kindly request that Rainbow stops attempting to conceal and obscure this matter, until it is resolved.**

### CODE REVIEW

**Comment by welps** [comment]
> Hello all,
> I have written previously about Rainbow falsely advertising a "free mint" on its app, and then subsequently charging an ethereum fee (in addition to the gas required to mint the NFT) without my knowledge or consent. When this matter was brought to the attention of Rainbow representatives, Rainbow inexplicably advised me to contact the Ethereum Foundation, to recoup the funds owed to me by Rainbow. 
> 
> Rainbow has continued to attempt to evade accountability. Thus I am asking the broader community for advice and assistance on resolving this matter. I am also kindly requesting that Rainbow stops attempting to conceal and obscure this matter, including its deleting of these communications, until this matter is resolved.  
> 
> The only way to communicate with Rainbow representatives has been on Github. In response, Rainbow has attempted to delete all evidence of these communications, and then communicating with me privately, while exerting no actual effort in resolving this matter, as demonstrated by Rainbow's latest response: 
> 
> On Sun, May 12, 2024 at 9:59 AM MK <[notifications@github.com](mailto:notifications@github.com)> wrote:
>  **I know this is super frustrating, but please let's keep the conversation in this discussion [#1960](https://github.com/rainbow-me/rainbowkit/discussions/1960). Like i said the team is looking at this issue and we'll contact you back as soon as possible. The issue is unknown at the moment and our team is investigating this. Thanks for your patience 🙏**
> 
> —
> 
> **I am requesting the community's help in seeking a resolution to this matter, and ensuring Rainbow holds itself accountable for its actions. I am also kindly request that Rainbow stops attempting to conceal and obscure this matter, until it is resolved.**

We don't have a medium. Any support issues should be sent to support@rainbow.me or https://support.rainbow.me. 

People are deleting your posts because these are developer repos and not customer support forums.

**Comment by DayOfShah** [comment]
Hi Welps, thank you for your response. 

I understand that you likely have no ill-intent when closing these threads, and are likely doing so because you believe they are being posted in an incorrect setting. However given the fraud that runs rampant in this industry, and the negative impact that fraud has on the community at large, I implore you to consider the importance of your employer being help accountable for engaging in the defrauding of its own community

Also, to clarify, communications have been sent directly to support@rainbow.me and went unacknowledged. It was only upon communicating via Github, did Rainbow provide a response. 

Thus, what reason is there to believe that Rainbow will resolve this matter if it is again made private?

I hope you have a great day. It shows great dilligence for you to be working on a Sunday. I wish prosperity and joy for you and your loved ones

**Comment by welps** [comment]
@DayOfShah I've pinged internal support about this to see what happened.

**Comment by welps** [comment]
@DayOfShah Can you send support@rainbow.me the mint transaction again and cc me so I can make sure it's properly tracked? wayne@rainbow.me

Thanks

**Comment by DayOfShah** [comment]
How is it possible that the previous communications claimed Rainbow was
"working on it" but this is the first time Rainbow is requesting the
transaction ID?

https://basescan.org/tx/0x670bf0232b39581058602286d058e1c7815a9bb98bf1c4a068f3a93398d805ff
https://basescan.org/tx/0xa39d40216d26962e20a9ee5cce600a40cc1395adfadb80a34b19289375afb35b

**Comment by welps** [comment]
@DayOfShah I am trying to figure out what happened which is why I requested you reach out again to the email address and CC me. Please do not jump to conclusions. Thank you.

**Comment by welps** [comment]
@DayOfShah Support team has refunded you here: https://basescan.org/tx/0xeb567e3d58f1bb58c304850c9d89e0b60379b4285d275bd7711588adcac18753

**Pull request closed without merging**
